// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE9PfJRfyuwWIS5vo0mXy2RMj2H0DewDo',
    appId: '1:557079151932:web:47ea3fd2c3ca488c7fca39',
    messagingSenderId: '557079151932',
    projectId: 'chat-app-97668',
    authDomain: 'chat-app-97668.firebaseapp.com',
    storageBucket: 'chat-app-97668.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUHYwCds4WKcvH-O8CUpprKYTWjYxSRbA',
    appId: '1:557079151932:android:dfa5ef9f076bd5067fca39',
    messagingSenderId: '557079151932',
    projectId: 'chat-app-97668',
    storageBucket: 'chat-app-97668.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7B9lZjcwdQxoDHvzqjkdaZsKiGy8BYFk',
    appId: '1:557079151932:ios:a248c9f4520506a17fca39',
    messagingSenderId: '557079151932',
    projectId: 'chat-app-97668',
    storageBucket: 'chat-app-97668.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7B9lZjcwdQxoDHvzqjkdaZsKiGy8BYFk',
    appId: '1:557079151932:ios:425ebac5667f75897fca39',
    messagingSenderId: '557079151932',
    projectId: 'chat-app-97668',
    storageBucket: 'chat-app-97668.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
